gürbüz = input("Gürbüz kim olsun? Seçenekler: Nazlı , Gürbüz , Kekstra: ")
nazli = input("Nazlı kim olsun? Seçenekler: Nazlı , Gürbüz , Kekstra: ")
kekstra = input("Kekstra kim olsun? Seçenekler: Nazlı , Gürbüz , Kekstra: ")
kek = kekstra
print()
print(gürbüz + " tam bir canavar herkes ondan korkar.")
print()
print("Kapıda görünür görünmez saklanır " + kekstra + "lar.")
print()
print(nazli + " okul birincisi " + kekstra + " tek eğlencesi.")
print()
print("Tam "+ kekstra +"sını yerken "+ gürbüz +" yanına geldi.")
print()
print(nazli + " kafayı kullandı "+ kekstra +"yı ters çevirdi.")
print()
print("Jölesi altta kalınca "+ gürbüz +" onu "+ kek[::-1] +" sandı.")
print()
print(gürbüz + " gittiği anda "+ kek[::-1] +" yine "+ kekstra +" oldu.")
print()
print(nazli + " jöleli kremanın tadına yine doydu.")
print()
print("Aaaa a a a " + kek[::-1] + " değil " + kekstra + ".")
